# Spring Application Name
spring.application.name=managewise-backend

# Spring DataSource Configuration (modificado para Render)
spring.datasource.url=jdbc:postgresql://dpg-d1o7np3uibrs73cdu14g-a.oregon-postgres.render.com/managecorebd
spring.datasource.username=managecorebd_user
spring.datasource.password=vG7vy6sfoBg44I9QFOWwCQycSrcqhjUb
spring.datasource.driver-class-name=org.postgresql.Driver

# Spring Data JPA Configuration
spring.jpa.database=postgresql
spring.jpa.show-sql=true

# Spring Data JPA Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.physical-strategy=pe.edu.upc.managewise.backend.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy

# reCAPTCHA
recaptcha.secret=6LegDH4rAAAAAOLluijGrHNQQfZYyN8ndB9pLYNi
recaptcha.verify.url=https://www.google.com/recaptcha/api/siteverify

#*****************iam************************

# Application Information for Documentation
documentation.application.description=@project.description@
documentation.application.version=@project.version@

# JWT Configuration Properties
authorization.jwt.secret=WriteHereYourSecretStringForTokenSigningCredentials
authorization.jwt.expiration.days=7

#*****************iam************************

# Habilitar endpoints de metricas
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true

